spring:
  payments:
    phonepe:
      merchantId: ${PHONEPE_MERCHANT_ID}
      saltKey: ${PHONEPE_SALT_KEY}
      saltIndex: ${PHONEPE_SALT_KEY_INDEX}
      env: UAT
      shouldPublishEvents: true
      callbackUrl: http://localhost:8080/pay-return-url